### ISSUE TITLE
implementação da tela de detalhe, comentário e novo comentário

### ISSUE THREAD

**Issue by sombriks** [sombriks/ifce-2018.1-psi#17]

**Comment by tavares1** [comment]
Definir como será a transição da tela de anuncio para detalhe, e como ficará a organização dos componentes da tela.

**Comment by sombriks** [comment]
@tavares1 aqui no routers.js: https://github.com/sombriks/ifce-2018.1-psi/blob/master/src/components/routes.js

tem uns mapeamentos feitos, mas realmente o firebase tá tendo um impacto maior do que o esperado.

por exemplo, o mapeamento pra detalhe previa uma chave com nome "idanuncionanimal", mas o que será passado é a ".key", criada pelo firebase.

não muda nada no roteamento (e nem no nome da variável que vier pelo $route.params), mas muda de onde buscamos nos resultados do firebase.
