### ISSUE TITLE
implementação da tela de profile 

### ISSUE THREAD

**Issue by emanuellucascomp** [sombriks/ifce-2018.1-psi#20]

**Comment by emanuellucascomp** [comment]
Commit na branch faltando a implementação da lista, selecionando apenas do usuário logado. Acredito que devemos mudar esse detalhe no banco, para receber como parâmetro o email (ou qualquer outra chave que diferencie o usuário). A tela de atualizar o perfil está faltando implementar a lógica. @sombriks @tavares1 se tiverem alguma observação a fazer

**Comment by sombriks** [comment]
a tela irá ser reestruturada
