### ISSUE TITLE
estudo de vue.js

### ISSUE THREAD

**Issue by sombriks** [sombriks/ifce-2018.1-psi#3]
- https://vuejs.org/v2/guide/join.html
- https://router.vuejs.org/en/
- https://vuetifyjs.com/en/
- https://vuejs-tips.github.io/cheatsheet/

**Comment by JoaoAdalberto** [comment]
- [ ] Vue

- [ ] Diagrama Ciclo de Vida

- [ ]Vue Router

**Comment by JoaoAdalberto** [comment]
- [x] Vue

- [x] Diagrama Ciclo de Vida

- [x] Vue Router
