### ISSUE TITLE
definição de entidade: amigoanimal

### ISSUE THREAD

**Issue by sombriks** [sombriks/ifce-2018.1-psi#6]
amigoanimal é a entidade básica das pessoas que decidirem cadastrar novos anuncios ou comentar anuncios

para listar anuncios não é preciso estar logado, mas é preciso fazer login e ser um amigoanimal pra poder comentar ou subir um novo anuncioanimal

**Comment by emanuellucascomp** [comment]
![amigoanimal](https://user-images.githubusercontent.com/24272264/36952564-74bdab82-1ff0-11e8-8c2b-eb51c85e7f0b.PNG)

**Comment by emanuellucascomp** [comment]
@sombriks acredito que dessa forma está correta, ou bem próximo disso, pode dar uma olhada antes de fechar a issue? os outros entes também estão modelados
